version: 0.2
phases:
  build:
    commands:
      - npm install
      - npm run dev
artifacts:
  files:
    - index.html
    - favicon.ico
    - WieslawPedzich-Resume.pdf
    - images/*
    - styles/*
    - dist/bundle.js
